= Specification for Git Tree Serialization Target
Joey Carpinelli <joseph.carpinelli@icloud.com>

[abstract]
****
New reflection primitives, e.g. the `Facet` trait provided by https://facet.rs[`facet`], allow for simpler runtime inspection of deserialized data.
This project uses `facet` to encode data of arbitrary shapes into Git trees.
The invariants and functionality described here will be upheld (and expanded) while the project is developed.
****

== Requirements

The following requirements define the expected behavior of the Git tree serialization and deserialization targets.

[CAUTION]
====
This set of requirements is not yet stable, and will grow (and change) over time.
====

=== Compatibility

[role="requirement", id="compatibility.facet"]
.Compatibility with the Facet Ecosystem
--
The `facet-git-tree` crate MUST satisfy all requirements of general `facet` adapter crates.
--

[role="requirement", id="compatibility.update"]
.Compatibility with Prior Releases
--
The `facet-git-tree` crate MUST strictly adhere to semantic versioning.
--


[role="requirement", id="compatibility.git"]
.Compatibility with Git
--
The `facet-git-tree` crate MUST be compatible with Git's v2 object format.
--

=== Serialization

[role="requirement", id="serialization.mechanism"]
.Serialization Mechanism
--
The `facet-git-tree` crate MUST provide a struct which can be serialized into Git trees using only the `Facet` trait.
--

[role="requirement", id="serialization.design.leaves"]
.Serialization Design
--
Data which is not a collection, and which is not represented by another schema object, MUST be stored in UTF-8 encoded Git blobs.
--

[role="requirement", id="serialization.design.trees.schemas"]
.Schema Object Encoding
--
Schema objects MUST be encoded as Git trees with a `.schema` sentinel entry which holds a tree that represents the `facet` type's `SHAPE`.
--

[role="requirement", id="serialization.design.trees.shape"]
.Assumed Schema Shape
--
The identity of a type encoded by `.schema` is always recorded as an identifier (unique to the particular `.schema` tree) in an `id` tree entry that resolves to a blob.
Definitions are recorded in a flattened `defs` subtree which references identifiers, and never a full schema tree.

[IMPORTANT]
====
This is required to avoid cycles in type definitions.
Values are inherently cycle-free due to Git's DAG data model.
====
--

[role="requirement", id="serialization.design.trees.collections"]
.Provided Collection Types
--
The following standard collections in Rust MUST be provided as built-in `facet` types, each with their own `.schema` entry value.

. Array
. Vec
. Map
--

[role="requirement", id="serialization.design.normalization.leaves"]
.Normalizing Leaves
--
The following leaf representations MUST be normalized on-write.

. Negative zero MUST be normalized to positive zero.
. The _not a number_ (`nan`) value MUST be normalized to the unquoted string `nan`.
--

=== Deserialization

[role="requirement", id="deserialization.roundtrip"]
.Support for Serialization and Deserialization
--
Deserialization of a data which was serialized via `facet-git-tree` MUST result in the original data.
--

=== Structural Comparison

[role="requirement", id="structural.comparison.equality"]
.Structural Equality
--
If two data instances serialize to the same Git tree, they MUST be considered equal for purposes of data retention.
--

[role="requirement", id="structural.comparison.diff"]
.Structural Differencing
--
A Git diff driver MUST be provided which supports comparing `facet` data structurally, assuming the `facet-git-tree` shape.

[NOTE]
====
Due to limitations in the `git` CLI's `diff` algorithm selection, `git show` and `git diff` will ALWAYS use a user's configured `diff` driver and not the driver provided by `facet-git-tree`.
Regardless, tooling which specifically targets `facet-git-tree` will benefit from the structural differencing driver.
====
--
